vich_uploader:
    db_driver: orm

    metadata:
        type: attribute



    mappings:
        user_avatar:
            uri_prefix: /avatars
            upload_destination: '%kernel.project_dir%/public/avatars'
            namer:
                service: vich_uploader.namer_origname
