controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_edit-with-password:
    path: '/user/edit-with-password/{id}'
    controller: App\Controller\UserController::modifier